language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"

before_install:
  - apt-get install python-pip
  - pip install pytest pytest-cov
  - pip install python-coveralls

script: py.test --cov rpn.py

after_success: coveralls
