language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"

install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install termcolor

script: coverage run -m unittest discover

after_success: coveralls
